### ISSUE TITLE
findWBD breaks topology

### ISSUE THREAD

**Issue by jsta** [mikejohnson51/HydroData#29]
I believe HUCs should be non-overlapping. However this test fails:

```r
library(sf)
library(HydroData)
bb <- st_as_sfc(st_bbox(c(xmin = -97.36394, xmax = -89.70397,
                ymax = 46.35289, ymin = 40.31668), crs = st_crs(4326)))

h4s <- findWBD(getAOI(bb), level = 4, crop = FALSE)
all(sapply(st_overlaps(st_as_sf(h4s$huc4)), length) == 0)
```

**Comment by mikejohnson51** [comment]
Hi Joseph,

Thanks! This is an interesting point.

Looking at two offenders from your example:

```r
library(leaflet)
leaflet() %>% addTiles() %>% addPolygons(data = h4s$huc4[c(1,8), ])
```

doesn't reveal any obvious overlap. Since this is a big request (25 HUC4s) it is coming from the staged USGS data found at their FTP - so a pretty nice dataset. 

My guess is this is not a break in topology but rather a byproduct of findWBD() downloading and returning a merged file of polygons features.

Each feature is a unique, complete HUC boundary so any lines shared by two adjacent HUCs (eg 1 and 8) will be contained in the polygon of both feature 1 and 8. Therefore when compared, those lines will overlap simply because they are identical. I do not believe they are crossing each other in anyway so this issue should not impact any sort of analysis.

Let me know if you think I am off on this!

Mike
